apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-dev-config-server
  namespace: petclinic-dev
  labels:
    app: petclinic-dev-config-server
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: petclinic-dev-config-server
  template:
    metadata:
      labels:
        app: petclinic-dev-config-server
    spec:
      containers:
        - name: config-server
          image: 527582557964.dkr.ecr.us-east-1.amazonaws.com/petclinic-dev-config-server:latest
          ports:
            - containerPort: 8888
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "384Mi"
              cpu: "200m"
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "docker"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8888
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8888
            initialDelaySeconds: 60
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: petclinic-dev-config-server
  namespace: petclinic-dev
spec:
  selector:
    app: petclinic-dev-config-server
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
